version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_INITDB_CHARSET=utf8mb4
    command: >
      bash -c "
      chmod 644 /etc/mysql/mysql.conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - ./sql/mock:/docker-entrypoint-initdb.d
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqld.cnf:/etc/mysql/my.cnf

  backend-api:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 3001:3001
