version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    volumes:
      - ./sql/mock:/docker-entrypoint-initdb.d

    networks:
      - backend

  backend-api:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 3001:3001

    networks:
      - backend

volumes:
  db:

networks:
  backend:
